### ISSUE TITLE
Version number of arrowhead client should be 4.1.0

### ISSUE THREAD

**Issue by fortikeco** [arrowhead-f/client-java#8]
I noticed that, although the core is version 4.1.0, the client git tag for 4.1.0 and master currently have the version number 4.0 in the pom file. Could the version number be bumped?

**Comment by hegeduscs** [comment]
The clients are not versioned according to the core systems entirely. 

They are versioned by having "major.patch" semantic versioning, where the major of the clients correspond to the core systems' major number (i.e. REST interface compatibility), while the minor of the clients is merely a patch number.

**Comment by fortikeco** [comment]
Seems to me that versioning schematic is very unusual!


Op wo 6 mrt. 2019 om 09:05 schreef Csaba Hegedus <notifications@github.com>:

**Comment by hegeduscs** [comment]
Well, that happens when we have several core modules developed separately, with separate versioning and with various client types that interact with various core systems. 

The clients are versioned with having their major number correspond to the major number of the core system they are interacting with: 
- consumer: orchestrator
- provider: serviceregistry
- publisher, subscriber: eventhandler

**Comment by fortikeco** [comment]
Thanks for your answer! Is there a possibility then that the arrowhead-client 4.0 jar (although it then is compatible with 4.1.0 services) gets uploaded to the Maven Central Repository? Right now, I make the client be part of our services and include all the code, which is actually unmaintainable. A dependency would be more logical.
